name: Publish Package to npmjs
on:
  release:
    types: [published]

# Permission to generate an OIDC token
permissions:
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # get the non-merge commit for PRs
          fetch-tags: true # include tags to get correct git version

      - uses: actions/setup-node@v6
        with:
          node-version: '23.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install meson and build toolchain
        run: |
          sudo apt update -y
          sudo apt install -y meson ninja-build build-essential

      # Install emscripten https://emscripten.org/docs/getting_started/downloads.html
      # Don't use apt, it installs an ANCIENT version of emscripten even in 24.04
      - name: Install emscripten
        run: |
          # Get the emsdk repo
          git clone https://github.com/emscripten-core/emsdk.git

          # Enter that directory
          cd emsdk
          # Download and install the latest SDK tools.
          ./emsdk install latest

          # Make the "latest" SDK "active" for the current user. (writes .emscripten file)
          ./emsdk activate latest

          # Activate PATH and other environment variables in the current terminal
          source ./emsdk_env.sh


      - name: Install node dependencies and build the project
        run: |
          npm ci
          npm run build

      # https://hackernoon.com/how-to-automatically-publish-your-npm-package-using-github-actions
      # Here we actually use `npm version from-git`, but just never commit the version.
      - name: Update package.json with release tag
        run: |
          npm version from-git --no-git-tag-version --allow-same-version

      - run: npm publish --provenance --access public
