name: Publish Package to npmjs
on:
  release:
    types: [published]

# See https://docs.npmjs.com/trusted-publishers#step-2-configure-your-cicd-workflow

# Permission to generate an OIDC token
permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # get the non-merge commit for PRs
          fetch-tags: true # include tags to get correct git version

      - name: Install meson and build toolchain
        run: |
          sudo apt update -y
          sudo apt install -y meson ninja-build build-essential

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 5.0.1

      - uses: actions/setup-node@v6
        with:
          node-version: '25'
          registry-url: 'https://registry.npmjs.org'

      # https://hackernoon.com/how-to-automatically-publish-your-npm-package-using-github-actions
      # Here we actually use `npm version from-git`, but just never commit the version.
      - name: Install node dependencies and build the project
        run: |
          npm ci
          npm version from-git --no-git-tag-version --allow-same-version
          npm run build
          npm publish --provenance --access public
